# Generated by Django 4.0.1 on 2022-01-29 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0003_scholar_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_name', models.CharField(max_length=256)),
                ('si_description', models.TextField()),
                ('si_total_amount', models.IntegerField()),
                ('si_individual_amount', models.IntegerField()),
                ('si_max_scholar', models.IntegerField()),
                ('si_remain_scholar', models.IntegerField()),
                ('si_source', models.CharField(max_length=256)),
                ('si_source_name', models.JSONField()),
                ('si_photo_bg', models.ImageField(upload_to='uploads/info')),
                ('si_path_to_pdf', models.FileField(upload_to='documents/info')),
                ('si_note', models.TextField()),
                ('si_sub_type', models.TextField()),
                ('si_grade_require', models.FloatField()),
                ('si_create_time', models.DateField(default=django.utils.timezone.now)),
                ('si_expire_time', models.DateField()),
                ('si_year', models.CharField(max_length=4)),
                ('si_semester', models.IntegerField()),
            ],
        ),
    ]
