# Generated by Django 4.0.1 on 2022-02-01 07:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0005_alter_scholar_info_si_photo_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_info',
            name='si_photo_bg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[1280, 720], upload_to='uploads/info'),
        ),
    ]
