# Generated by Django 4.0.1 on 2022-02-01 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0006_alter_scholar_info_si_photo_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='manage_commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_sp_g_id', models.CharField(max_length=64)),
                ('sc_mail', models.CharField(max_length=64)),
                ('sc_firstname', models.CharField(max_length=64)),
                ('sc_lastname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar_weight_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sws_info', models.JSONField()),
                ('sws_date', models.DateField(default=django.utils.timezone.now)),
                ('sws_si_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info')),
            ],
        ),
    ]
