# Generated by Django 4.0.1 on 2022-02-01 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0007_manage_commit_scholar_weight_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_commit',
            name='sc_firstname',
        ),
        migrations.RemoveField(
            model_name='manage_commit',
            name='sc_lastname',
        ),
        migrations.RemoveField(
            model_name='manage_commit',
            name='sc_mail',
        ),
        migrations.AlterField(
            model_name='manage_commit',
            name='sc_sp_g_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
