# Generated by Django 4.0.1 on 2022-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0008_remove_manage_commit_sc_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_email', models.CharField(max_length=256)),
                ('ac_fistname', models.CharField(max_length=256)),
                ('ac_lastname', models.CharField(max_length=256)),
            ],
        ),
    ]
