# Generated by Django 4.0.1 on 2022-02-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0009_add_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_commit',
            old_name='ac_fistname',
            new_name='ac_firstname',
        ),
    ]
