# Generated by Django 4.0.1 on 2022-02-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0010_rename_ac_fistname_add_commit_ac_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_commit',
            name='access_Scholar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info'),
        ),
        migrations.AddField(
            model_name='scholar_weight_score',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Scholar_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_advisor_professor', models.CharField(max_length=64)),
                ('sp_status', models.IntegerField()),
                ('sp_title_en', models.CharField(max_length=8)),
                ('sp_firstname_en', models.CharField(max_length=64)),
                ('sp_middlename_en', models.CharField(max_length=64)),
                ('sp_lastname_en', models.CharField(max_length=64)),
                ('sp_std_code', models.CharField(max_length=10)),
                ('sp_title_th', models.CharField(max_length=8)),
                ('sp_firstname_th', models.CharField(max_length=64)),
                ('sp_middlename_th', models.CharField(max_length=64)),
                ('sp_lastname_th', models.CharField(max_length=64)),
                ('sp_path_to_avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='uploads/avatar')),
                ('sp_date_of_birth', models.DateField()),
                ('sp_major', models.CharField(max_length=4)),
                ('sp_grade', models.CharField(max_length=4)),
                ('sp_path_to_pdf_json', models.JSONField()),
                ('sp_std_address', models.JSONField()),
                ('sp_std_tel_no', models.CharField(max_length=10)),
                ('sp_father_title', models.CharField(max_length=8)),
                ('sp_father_firstname', models.CharField(max_length=64)),
                ('sp_father_middlename', models.CharField(max_length=64)),
                ('sp_father_lastname', models.CharField(max_length=64)),
                ('sp_father_date_of_birth', models.DateField()),
                ('sp_father_age', models.IntegerField()),
                ('sp_father_status_married', models.CharField(max_length=64)),
                ('sp_father_statuslife', models.CharField(max_length=64)),
                ('sp_father_income', models.IntegerField()),
                ('sp_father_career', models.CharField(max_length=64)),
                ('sp_father_workplace', models.CharField(max_length=128)),
                ('sp_father_address', models.JSONField()),
                ('sp_father_tel_no', models.CharField(max_length=10)),
                ('sp_mother_title', models.CharField(max_length=8)),
                ('sp_mother_firstname', models.CharField(max_length=64)),
                ('sp_mother_middlename', models.CharField(max_length=64)),
                ('sp_mother_lastname', models.CharField(max_length=64)),
                ('sp_mother_address', models.JSONField()),
                ('sp_mother_date_of_birth', models.DateField()),
                ('sp_mother_age', models.IntegerField()),
                ('sp_mother_status_married', models.CharField(max_length=64)),
                ('sp_mother_statuslife', models.CharField(max_length=64)),
                ('sp_mother_income', models.IntegerField()),
                ('sp_mother_career', models.CharField(max_length=64)),
                ('sp_mother_workplace', models.CharField(max_length=128)),
                ('sp_mother_tel_no', models.CharField(max_length=10)),
                ('sp_bro_n_sis', models.JSONField()),
                ('sp_loan', models.CharField(max_length=32)),
                ('sp_income', models.IntegerField()),
                ('sp_income_source', models.CharField(max_length=32)),
                ('sp_patron_relation', models.CharField(max_length=32)),
                ('sp_patron_career', models.CharField(max_length=64)),
                ('sp_patron_tel_no', models.CharField(max_length=64)),
                ('sp_patron_workplace', models.JSONField()),
                ('sp_child_in_the_patron', models.IntegerField()),
                ('sp_parttime', models.CharField(max_length=1)),
                ('sp_parttime_income', models.IntegerField()),
                ('sp_parttime_type', models.CharField(max_length=128)),
                ('sp_received_scholar', models.CharField(max_length=128)),
                ('sp_year_received_scholar', models.CharField(max_length=4)),
                ('sp_money_received_scholar', models.IntegerField()),
                ('sp_report', models.TextField()),
                ('sp_userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
