# Generated by Django 4.0.1 on 2022-02-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0011_manage_commit_access_scholar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_commit',
            name='access_Scholar_id',
        ),
    ]
