# Generated by Django 4.0.1 on 2022-02-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0012_remove_manage_commit_access_scholar_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manage_commit',
        ),
    ]
