# Generated by Django 4.0.1 on 2022-02-05 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0019_rename_scholar_profile2_scholar_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_title', models.CharField(max_length=200, verbose_name='Title')),
                ('fm_file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File')),
                ('fm_Scholar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info')),
                ('fm_upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
