# Generated by Django 4.0.1 on 2022-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0020_file_models_delete_mymodel'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='scholar_info',
            name='si_grade_require',
            field=models.FloatField(null=True),
        ),
    ]
