# Generated by Django 4.0.1 on 2022-02-06 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0021_remove_file_models_fm_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar_info',
            options={'ordering': ['-si_create_time']},
        ),
        migrations.AlterModelOptions(
            name='scholar_news',
            options={'ordering': ['-sn_create_time']},
        ),
        migrations.AddField(
            model_name='scholar_news',
            name='sn_create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
