# Generated by Django 4.0.1 on 2022-02-08 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0024_remove_scholar_profile_sp_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_profile',
            name='sp_userid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
