# Generated by Django 4.0.1 on 2022-02-10 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0026_alter_scholar_profile_sp_advisor_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_father_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_mother_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
