# Generated by Django 4.0.1 on 2022-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0027_alter_scholar_profile_sp_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_child_in_the_patron',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_father_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_father_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_money_received_scholar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_mother_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_mother_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_profile',
            name='sp_parttime_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
