# Generated by Django 4.0.1 on 2022-02-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0030_alter_scholar_profile_sp_father_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_status', models.IntegerField()),
                ('sa_score', models.IntegerField()),
                ('sa_score_info', models.JSONField()),
                ('sa_path_to_pdf', models.FileField(upload_to='documents/info')),
                ('sa_si_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info')),
                ('sa_sp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_profile')),
            ],
        ),
        migrations.CreateModel(
            name='add_scholar_Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholar_name', models.ManyToManyField(to='etune.Scholar_info')),
                ('id_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etune.add_commit')),
            ],
        ),
    ]
