# Generated by Django 4.0.1 on 2022-02-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0032_scholar_app_sa_userid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholar_app',
        ),
    ]
