# Generated by Django 4.0.1 on 2022-02-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0034_scholar_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholar_app',
        ),
    ]
