# Generated by Django 4.0.1 on 2022-02-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0035_delete_scholar_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_status', models.IntegerField()),
                ('sa_score', models.IntegerField(blank=True)),
                ('sa_score_info', models.JSONField()),
                ('sa_path_to_pdf', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File')),
                ('sa_si_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info')),
                ('sa_sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_profile')),
                ('sa_userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
