# Generated by Django 4.0.1 on 2022-02-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0036_scholar_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_scholar_commit',
            name='Scholar_name',
        ),
        migrations.AddField(
            model_name='add_scholar_commit',
            name='Scholar_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info'),
            preserve_default=False,
        ),
    ]
