# Generated by Django 4.0.1 on 2022-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0037_remove_add_scholar_commit_scholar_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_scholar_commit',
            name='Scholar_name',
        ),
        migrations.AddField(
            model_name='add_scholar_commit',
            name='Scholar_name',
            field=models.ManyToManyField(to='etune.Scholar_info'),
        ),
    ]
