# Generated by Django 4.0.1 on 2022-02-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0040_remove_add_scholar_commit_scholar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_profile',
            name='sp_json_scholar',
            field=models.JSONField(null=True),
        ),
    ]
