# Generated by Django 4.0.1 on 2022-02-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0042_remove_scholar_profile_sp_money_received_scholar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_si_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info'),
        ),
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
