# Generated by Django 4.0.1 on 2022-02-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0043_alter_scholar_app_sa_si_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_profile',
            name='sp_path_to_avatar',
        ),
        migrations.CreateModel(
            name='avatar_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_path_to_avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='uploads/avatar')),
                ('sa_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
