# Generated by Django 4.0.1 on 2022-02-17 17:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0046_alter_avatar_profile_sa_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar_profile',
            name='sp_path_to_avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static/images/noimg.png', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='uploads/avatar'),
        ),
    ]
