# Generated by Django 4.0.1 on 2022-02-18 09:05

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0050_alter_avatar_profile_sp_path_to_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar_profile',
            name='sp_path_to_avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='noimg.png', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='uploads/avatar'),
        ),
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_status',
            field=models.IntegerField(default=11),
        ),
    ]
