# Generated by Django 4.0.2 on 2022-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0054_alter_scholar_app_sa_advisor_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_profile',
            name='sp_path_to_pdf_json',
        ),
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score',
            field=models.IntegerField(blank=True),
        ),
    ]
