# Generated by Django 4.0.2 on 2022-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0055_remove_scholar_profile_sp_path_to_pdf_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
