# Generated by Django 4.0.2 on 2022-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0056_alter_scholar_app_sa_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score_info',
            field=models.JSONField(null=True),
        ),
    ]
