# Generated by Django 4.0.2 on 2022-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0057_alter_scholar_app_sa_score_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score_info',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
