# Generated by Django 4.0.2 on 2022-02-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etune', '0059_alter_file_models_fm_scholar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_models',
            name='fm_Scholar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etune.scholar_info'),
        ),
        migrations.AlterField(
            model_name='file_models',
            name='fm_upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
