# Generated by Django 4.0.2 on 2022-02-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0061_alter_file_models_fm_scholar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_score',
            field=models.FloatField(default=0),
        ),
    ]
