# Generated by Django 4.0.2 on 2022-02-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0062_alter_scholar_app_sa_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_models',
            name='fm_state',
            field=models.IntegerField(default=0),
        ),
    ]
