# Generated by Django 4.0.2 on 2022-02-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0066_scholar_info_si_photo_bg_scholar_news_sn_path_to_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_info',
            name='si_path_to_pdf',
            field=models.FileField(default=1, upload_to='documents/info'),
            preserve_default=False,
        ),
    ]
