# Generated by Django 4.0.2 on 2022-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0067_scholar_info_si_path_to_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_news',
            name='sn_photo_bg',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
