# Generated by Django 4.0.2 on 2022-02-25 05:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0068_alter_scholar_news_sn_photo_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_news',
            name='sn_photo_bg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[1280, 720], upload_to='uploads/'),
        ),
    ]
