# Generated by Django 4.0.2 on 2022-02-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0070_scholar_app_sa_jsoncommit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_app',
            name='sa_report',
        ),
        migrations.AddField(
            model_name='scholar_app',
            name='sa_fm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etune.file_models'),
            preserve_default=False,
        ),
    ]
