# Generated by Django 4.0.2 on 2022-02-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0071_remove_scholar_app_sa_report_scholar_app_sa_fm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_app',
            name='sa_fm_id',
        ),
    ]
