# Generated by Django 4.0.2 on 2022-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0072_remove_scholar_app_sa_fm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_jsoncommit',
            field=models.JSONField(default=[]),
        ),
    ]
