# Generated by Django 4.0.2 on 2022-02-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0073_alter_scholar_app_sa_jsoncommit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_jsoncommit',
            field=models.JSONField(default='{}'),
        ),
    ]
