# Generated by Django 4.0.2 on 2022-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0079_alter_scholar_app_sa_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_score',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
