# Generated by Django 4.0.2 on 2022-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0080_log_score_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_score',
            name='status',
        ),
        migrations.AddField(
            model_name='scholar_app',
            name='status_commit',
            field=models.BooleanField(default=False),
        ),
    ]
