# Generated by Django 4.0.2 on 2022-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0081_remove_log_score_status_scholar_app_status_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_profile',
            name='sp_json_commit',
            field=models.JSONField(null=True),
        ),
    ]
