# Generated by Django 4.0.2 on 2022-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0082_scholar_profile_sp_json_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_app',
            name='status_commit',
        ),
        migrations.RemoveField(
            model_name='scholar_profile',
            name='sp_json_commit',
        ),
        migrations.AddField(
            model_name='scholar_app',
            name='sa_json_commit',
            field=models.JSONField(null=True),
        ),
    ]
