# Generated by Django 4.0.2 on 2022-02-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0083_remove_scholar_app_status_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_app',
            name='sa_json_commit',
            field=models.JSONField(default=[], null=True),
        ),
    ]
