# Generated by Django 4.0.2 on 2022-02-27 13:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0088_alter_scholar_app_sa_json_commit'),
    ]

    operations = [
       
    ]
