# Generated by Django 4.0.2 on 2022-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0089_alter_scholar_info_si_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_info',
            name='si_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
