# Generated by Django 4.0.2 on 2022-02-28 14:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0090_alter_scholar_info_si_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_info',
            name='si_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_news',
            name='sn_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
