# Generated by Django 4.0.2 on 2022-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0091_alter_scholar_info_si_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar_app',
            options={'ordering': ['-sa_score']},
        ),
        migrations.AddField(
            model_name='scholar_info',
            name='si_status',
            field=models.IntegerField(default=0),
        ),
    ]
