# Generated by Django 4.0.2 on 2022-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0092_alter_scholar_app_options_scholar_info_si_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_news',
            name='sn_status',
            field=models.IntegerField(default=0),
        ),
    ]
