# Generated by Django 4.0.2 on 2022-03-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0093_scholar_news_sn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_info',
            name='si_source_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
