# Generated by Django 4.0.2 on 2022-03-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etune', '0096_scholar_app_sa_statusdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_app',
            name='sa_statusDate',
        ),
    ]
